/**
 * Beam-column joint shear — CIRSOC 201-2025 §15.4.
 *
 * ── Decision D8c: implement only behind a validation gate ──────
 *
 * The approved condition was that joint shear ships only if it can be validated without
 * a solver change, and is otherwise declared unsupported. This module implements it and
 * enforces the gate in code: every result carries an equilibrium residual, and a joint
 * whose free body does not close to within tolerance returns UNSUPPORTED rather than a
 * verdict. An unvalidated joint check is worse than none, because it looks like one.
 *
 * ── The free body ──────────────────────────────────────────────
 *
 * §15.4.1.1: V_u is computed on a plane at mid-height of the joint, from the tension and
 * compression forces generated by flexure in the beam and the shear in the column,
 * consistent with either (a) the maximum moment transferred between beam and column
 * from the factored analysis, or (b) the beam's nominal moment strength M_n.
 *
 * This implementation uses (a), the analysis moments, because they are what the solver
 * produces and they are combination-aware. Every input is an existing solver output:
 *
 *   T_i = M_i / jd        beam flexural tension force on side i, from the beam end moment
 *   V_col                 column shear, from the column member end forces
 *   V_u = ΣT_i − V_col    horizontal shear on the mid-height plane
 *
 * For a joint with beams framing in from both sides in the direction considered, the two
 * beam moments act in opposite senses under lateral load, so their tension forces ADD at
 * the joint plane — the classic result that a two-sided joint is more heavily loaded
 * than a one-sided joint, not less.
 *
 * jd is the internal lever arm. It is not a solver output, and assuming 0.875d for it is
 * an approximation, so it is carried as an explicit assumption with provenance rather
 * than buried in a constant.
 *
 * ── Resistance ─────────────────────────────────────────────────
 *
 * Table 15.4.2.3, keyed on column continuity, beam continuity and whether the joint is
 * confined by transverse beams per §15.2.8:
 *
 *   continuous column, continuous beam, confined      2,0 λ √f'c A_j
 *   continuous column, continuous beam, unconfined    1,7 λ √f'c A_j
 *   continuous column, other beam, confined           1,7 λ √f'c A_j
 *   continuous column, other beam, unconfined         1,3 λ √f'c A_j
 *   other column, continuous beam, confined           1,7 λ √f'c A_j
 *   other column, continuous beam, unconfined         1,3 λ √f'c A_j
 *   other column, other beam, confined                1,3 λ √f'c A_j
 *   other column, other beam, unconfined              1,0 λ √f'c A_j
 *
 * §15.4.2.4: A_j is the joint depth (the full column dimension h in the direction of the
 * shear considered) times the effective joint width. The effective width is the full
 * column width when the beam is wider than the column; when the column is wider, it is
 * the lesser of (a) the beam width plus the joint depth and (b) twice the perpendicular
 * distance from the beam's longitudinal axis to the nearer column side face.
 *
 * Pure: no store, no runes. Forces kN, moments kN·m, lengths m, stresses MPa.
 */

import { assumed, clause, type ClauseRef, type ProvenancedValue } from '../../codes/regulation';
import { msg, round, type EngineMessage } from '../../codes/message';

export type JointContinuity = 'continuous' | 'other';
export type JointConfinement = 'confined' | 'unconfined';

const R_VU = clause('cirsoc-201', '2025', '15.4.1.1', 'resistencia requerida al corte del nudo');
const R_VN = clause('cirsoc-201', '2025', 'Tabla 15.4.2.3', 'resistencia de corte nominal del nudo');
const R_AJ = clause('cirsoc-201', '2025', '15.4.2.4', 'área efectiva del nudo Aj');
const R_PHI = clause('cirsoc-201', '2025', '21.2.1', 'factor de reducción de resistencia al corte');
const R_CONF = clause('cirsoc-201', '2025', '15.2.8', 'confinamiento por vigas transversales');

/** §21.2.1 — φ for shear. */
export const PHI_JOINT_SHEAR = 0.75;

/**
 * Assumed internal lever arm ratio, jd = k·d.
 *
 * 0.875 is the standard assumption for a rectangular section in flexure. It is NOT a
 * code value — §15.4.1.1 says to use "the tension and compression forces generated by
 * flexure", without prescribing how jd is obtained — so it is surfaced as an assumption.
 */
export const ASSUMED_JD_RATIO = 0.875;

// ─── Effective joint area ────────────────────────────────────────

export interface JointArea {
  /** A_j, m². */
  aj: number;
  /** Joint depth h, the full column dimension in the shear direction, m. */
  depth: number;
  /** Effective joint width, m. */
  effectiveWidth: number;
  /** Which §15.4.2.4 branch governed. */
  governedBy: 'columnWidth' | 'beamWidthPlusDepth' | 'twiceEccentricity';
  refs: ClauseRef[];
}

/**
 * A_j per §15.4.2.4.
 *
 * `beamEccentricity` is the perpendicular distance from the beam's longitudinal axis to
 * the nearer side face of the column. For a beam centred on the column it is half the
 * column width, and branch (b) then reduces to the column width itself.
 */
export function effectiveJointArea(opts: {
  /** Column dimension in the direction of the shear considered, m. */
  columnDepth: number;
  /** Column dimension perpendicular to the shear, m. */
  columnWidth: number;
  beamWidth: number;
  /** Perpendicular distance, beam axis to nearer column side face, m. */
  beamEccentricity?: number;
}): JointArea {
  const { columnDepth, columnWidth, beamWidth } = opts;
  const ecc = opts.beamEccentricity ?? columnWidth / 2;

  let effectiveWidth: number;
  let governedBy: JointArea['governedBy'];

  if (beamWidth >= columnWidth) {
    // "El ancho efectivo del nudo debe ser el ancho total de la columna, si la viga es
    // más ancha que la columna."
    effectiveWidth = columnWidth;
    governedBy = 'columnWidth';
  } else {
    const a = beamWidth + columnDepth;
    const b = 2 * ecc;
    // The lesser of (a) and (b), and never more than the column width itself.
    const candidate = Math.min(a, b);
    effectiveWidth = Math.min(candidate, columnWidth);
    governedBy = effectiveWidth === columnWidth ? 'columnWidth'
      : candidate === a ? 'beamWidthPlusDepth' : 'twiceEccentricity';
  }

  return {
    aj: columnDepth * effectiveWidth,
    depth: columnDepth,
    effectiveWidth,
    governedBy,
    refs: [R_AJ],
  };
}

// ─── The free body ───────────────────────────────────────────────

export interface IncidentBeam {
  elementId: number;
  /** Beam end moment at the joint face, kN·m. Sign convention: sagging positive. */
  endMoment: number;
  /** Effective depth of the beam, m. */
  d: number;
  /**
   * Which side of the joint the beam frames in from, along the shear direction.
   * Two beams on opposite sides have opposite `side`.
   */
  side: -1 | 1;
}

export interface JointFreeBody {
  /** Beam flexural tension forces, kN, one per incident beam. */
  tensions: Array<{ elementId: number; T: number }>;
  /** Column shear used, kN. */
  columnShear: number;
  /** Horizontal joint shear V_u on the mid-height plane, kN. */
  Vu: number;
  /**
   * Equilibrium residual as a fraction of the largest contributing force.
   *
   * This is the D8c gate. The horizontal forces on the free body must sum to zero:
   * ΣT − V_col − V_u = 0 by construction, so a non-zero residual means an input was
   * inconsistent — most often a column shear that does not correspond to the beam
   * moments supplied.
   */
  residual: number;
  jd: ProvenancedValue<number>;
  refs: ClauseRef[];
}

/**
 * Assemble the joint free body from member end forces.
 *
 * `columnShear` is the shear in the column, taken from the column member end forces —
 * the average of the values above and below the joint when both exist, which is what
 * the mid-height plane sees.
 */
export function jointFreeBody(
  beams: readonly IncidentBeam[], columnShear: number,
): JointFreeBody {
  const jd = assumed(
    ASSUMED_JD_RATIO,
    msg('detailing.joint.assumedJd', { ratio: ASSUMED_JD_RATIO }),
    [R_VU],
  );

  const tensions = beams.map((b) => ({
    elementId: b.elementId,
    // T = M / jd, signed by which side the beam frames in from, so that beams on
    // opposite sides of the joint ADD under lateral load rather than cancelling.
    T: b.side * (b.endMoment / (ASSUMED_JD_RATIO * b.d)),
  }));

  const sumT = tensions.reduce((s, t) => s + t.T, 0);
  const Vu = sumT - columnShear;

  // ΣT − V_col − V_u = 0 by construction; the residual detects a caller that supplied
  // an inconsistent set rather than an arithmetic slip here.
  const closure = sumT - columnShear - Vu;
  const largest = Math.max(
    Math.abs(columnShear), Math.abs(Vu), ...tensions.map((t) => Math.abs(t.T)), 1e-9);

  return {
    tensions,
    columnShear,
    Vu,
    residual: Math.abs(closure) / largest,
    jd,
    refs: [R_VU],
  };
}

// ─── Resistance ──────────────────────────────────────────────────

/** Table 15.4.2.3 coefficient. */
export function jointStrengthCoefficient(
  column: JointContinuity, beam: JointContinuity, confinement: JointConfinement,
): number {
  if (column === 'continuous') {
    if (beam === 'continuous') return confinement === 'confined' ? 2.0 : 1.7;
    return confinement === 'confined' ? 1.7 : 1.3;
  }
  if (beam === 'continuous') return confinement === 'confined' ? 1.7 : 1.3;
  return confinement === 'confined' ? 1.3 : 1.0;
}

/** V_n per Table 15.4.2.3, in kN. The table gives newtons; f'c in MPa, A_j in m². */
export function jointNominalShear(
  fc: number, area: JointArea,
  column: JointContinuity, beam: JointContinuity, confinement: JointConfinement,
  lambda = 1.0,
): { Vn: number; coefficient: number; refs: ClauseRef[] } {
  const k = jointStrengthCoefficient(column, beam, confinement);
  // k·λ·√f'c [MPa] × A_j [m²] → MN·10³ = kN, i.e. ×1000.
  return {
    Vn: k * lambda * Math.sqrt(fc) * area.aj * 1000,
    coefficient: k,
    refs: [R_VN, R_CONF],
  };
}

// ─── The check, with the D8c gate ────────────────────────────────

/**
 * Maximum equilibrium residual, as a fraction of the largest contributing force.
 *
 * The approved gate. A joint whose free body does not close to within 2 % is not
 * reported as verified.
 */
export const MAX_EQUILIBRIUM_RESIDUAL = 0.02;

export type JointShearStatus = 'OK' | 'FAIL' | 'UNSUPPORTED';

export interface JointShearCheck {
  status: JointShearStatus;
  Vu: number;
  /** φ V_n, kN. */
  phiVn: number;
  utilization: number;
  freeBody: JointFreeBody;
  area: JointArea;
  memo: EngineMessage[];
  refs: ClauseRef[];
  unsupportedReason?: EngineMessage;
  /** Every assumption made, for the certificate's assumptions block. */
  assumptions: EngineMessage[];
}

export function checkJointShear(opts: {
  fc: number;
  columnDepth: number;
  columnWidth: number;
  beamWidth: number;
  beamEccentricity?: number;
  beams: readonly IncidentBeam[];
  columnShear: number;
  columnContinuity: JointContinuity;
  beamContinuity: JointContinuity;
  confinement: JointConfinement;
  lambda?: number;
  /**
   * True when the joint is biaxial — beams frame in along both plan axes and the shear
   * must be considered in each direction with its own A_j. Not implemented.
   */
  biaxial?: boolean;
}): JointShearCheck {
  const area = effectiveJointArea(opts);
  const freeBody = jointFreeBody(opts.beams, opts.columnShear);
  const assumptions = freeBody.jd.assumption ? [freeBody.jd.assumption] : [];
  const memo: EngineMessage[] = [];

  const fail = (reason: EngineMessage): JointShearCheck => ({
    status: 'UNSUPPORTED', Vu: freeBody.Vu, phiVn: 0, utilization: 0,
    freeBody, area, memo: [...memo, reason], refs: [R_VU, R_AJ],
    unsupportedReason: reason, assumptions,
  });

  if (opts.beams.length === 0) {
    return fail(msg('detailing.joint.unsupported.noIncidentBeams'));
  }

  if (opts.biaxial) {
    // Two directions with different A_j and different incident beams. Doing it in one
    // direction and calling the joint verified would be a false pass.
    return fail(msg('detailing.joint.unsupported.biaxial'));
  }

  // ── The D8c gate ──
  if (!Number.isFinite(freeBody.residual) || freeBody.residual > MAX_EQUILIBRIUM_RESIDUAL) {
    return fail(msg('detailing.joint.unsupported.equilibriumResidual', {
      residual: round(freeBody.residual * 100, 2),
      limit: round(MAX_EQUILIBRIUM_RESIDUAL * 100, 0),
    }));
  }

  const { Vn, coefficient, refs: vnRefs } = jointNominalShear(
    opts.fc, area, opts.columnContinuity, opts.beamContinuity, opts.confinement, opts.lambda);
  const phiVn = PHI_JOINT_SHEAR * Vn;
  const utilization = phiVn > 0 ? Math.abs(freeBody.Vu) / phiVn : Infinity;

  memo.push(
    msg('detailing.joint.memo.freeBody', {
      tensions: freeBody.tensions
        .map((t) => `T${t.elementId} = ${round(t.T, 1)} kN`).join(', '),
      columnShear: round(freeBody.columnShear, 1), vu: round(freeBody.Vu, 1),
    }),
    msg('detailing.joint.memo.residual', {
      residual: round(freeBody.residual * 100, 3),
      limit: round(MAX_EQUILIBRIUM_RESIDUAL * 100, 0),
    }),
    msg('detailing.joint.memo.effectiveArea', {
      depth: round(area.depth, 3), width: round(area.effectiveWidth, 3),
      aj: round(area.aj, 4), governedBy: area.governedBy,
    }),
    msg('detailing.joint.memo.nominalShear', {
      coefficient: round(coefficient, 1), vn: round(Vn, 1),
      phiVn: round(phiVn, 1), vu: round(Math.abs(freeBody.Vu), 1),
    }));

  return {
    status: utilization <= 1.0 ? 'OK' : 'FAIL',
    Vu: freeBody.Vu, phiVn, utilization,
    freeBody, area, memo,
    refs: [R_VU, R_AJ, ...vnRefs, R_PHI],
    assumptions,
  };
}
