/**
 * PR17 — the coordinated detailing workflow in the browser, GENERATED not seeded.
 *
 * ── What changed and why ───────────────────────────────────────────
 *
 * Every test in this file used to call `seedDetailing(...)`, a Playwright hook that wrote
 * a hand-built assembly straight into the model. The forensic audit found that this hook
 * was the ONLY writer of `model.detailing` in the entire app: twenty-two green tests
 * describing a workflow no user could start. The tests were not wrong about the panel —
 * they were testing a panel fed by the test itself.
 *
 * Assemblies here are produced by clicking `Generate detailing`, the real command. The
 * upstream setup — load a model, solve, run the design — still goes through the hooks that
 * PR15's own real-user journeys cover; that is deliberate, and it is the line the rule
 * draws. Hooks may put the app in a starting position. They may not create the thing under
 * test. Nothing below creates an assembly, a bar, a mark, a conflict or a review record.
 *
 * States a single click cannot reach are reached the way a user would: SUPERSEDED by
 * changing an upstream input after reviewing, not by writing `state: 'SUPERSEDED'`.
 */

import { test, expect, designAll, loadModel } from './fixtures';

type Page = import('@playwright/test').Page;
type Json = Record<string, unknown>;

/**
 * Read the assemblies back. This is an OBSERVATION hook and stays: reading the store to
 * assert on what the UI produced is exactly what hooks are for.
 */
function assemblies(page: Page): Promise<Json[]> {
  return page.evaluate(() =>
    (window.__stabileo as unknown as { detailingAssemblies(): Json[] }).detailingAssemblies());
}

async function openPanel(page: Page) {
  const d = page.getByTestId('detailing-disclosure');
  await expect(d).toBeVisible();
  // Direct child only: the panel now contains nested disclosures of its own.
  await d.locator('> summary').click();
  return d;
}

/**
 * Put the app in a state where detailing CAN be generated, then generate it by clicking.
 *
 * Returns the number of assemblies the real pipeline produced.
 */
async function generateDetailing(page: Page): Promise<number> {
  await loadModel(page, 'rc-design-qa-8');
  await designAll(page);          // upstream setup — PR15's own journeys cover this path
  await openPanel(page);

  const button = page.getByTestId('cmd-generate-detailing');
  await expect(button, 'the Generate detailing command must be visible').toBeVisible();
  await expect(button, 'design produced verified members, so it must be enabled').toBeEnabled();
  await button.click();

  await expect.poll(async () => (await assemblies(page)).length, { timeout: 30_000 })
    .toBeGreaterThan(0);
  return (await assemblies(page)).length;
}

/** The first assembly's list entry. */
function firstAssembly(page: Page) {
  return page.locator('[data-testid^="assembly-"]').first();
}

// ─── Generation is reachable at all ──────────────────────────────

/**
 * Open the Documents stage.
 *
 * The professional review — the engineer's name, the notes, the provisional acknowledgements,
 * `Record review` and `Issue for construction` — moved out of the coordinated-detailing panel and
 * into a stage of its own. These assertions are unchanged; what changed is which disclosure holds
 * the controls, so they open that one too.
 */
async function openDocuments(page: import('@playwright/test').Page) {
  const d = page.getByTestId('documents-disclosure');
  if (await d.getAttribute('open') === null) await d.locator('> summary').click();
}

test.describe('@smoke detailing is generated by a visible command', () => {
  test('D1 — an empty project offers the command and names the prerequisites', async ({ pro: page }) => {
    await openPanel(page);
    await expect(page.getByTestId('detailing-empty')).toBeVisible();
    // The old empty state told the user to "run the detailing pipeline from the design
    // tab", which described a control that did not exist. It is the control now.
    const generate = page.getByTestId('detailing-empty-generate');
    await expect(generate).toBeVisible();
    await expect(generate).toBeDisabled();
    await expect(page.getByTestId('detailing-empty-prereqs')).toBeVisible();
  });

  test('D2 — Generate produces assemblies with real bars and marks', async ({ pro: page }) => {
    const n = await generateDetailing(page);
    expect(n).toBeGreaterThan(0);
    const a = (await assemblies(page))[0];
    expect((a.bars as unknown[]).length).toBeGreaterThan(0);
    expect((a.marks as unknown[]).length).toBeGreaterThan(0);
    // Every bar was PRODUCED by the pipeline, not seeded and not hand-entered.
    //
    // This asserted `'generated'` for every bar, which was true when it was written and
    // stopped being true at `52789e2b`: materialising the laps emits real steel with
    // `source: 'coordinated'` — a fused bar spanning a joint, or a lap the schedule turned
    // into a physical BarPath. Those are the opposite of a fixture; they are the steel the
    // coordinator added. The assertion has been failing since then, so it was measuring
    // nothing.
    //
    // What it should say, and now does: the pipeline's own two sources only, at least one
    // bar straight from the generator, and never `'manual'` — which is what a seeded or
    // hand-edited assembly would carry.
    const sources = (a.bars as Array<{ source: string }>).map((b) => b.source);
    expect(sources.length).toBeGreaterThan(0);
    for (const s of sources) expect(['generated', 'coordinated']).toContain(s);
    expect(sources).toContain('generated');
    expect(sources).not.toContain('manual');
  });

  test('D2b — the command relabels to Regenerate once assemblies exist', async ({ pro: page }) => {
    const button = page.getByTestId('cmd-generate-detailing');
    await loadModel(page, 'rc-design-qa-8');
    await designAll(page);
    await expect(button).toHaveText(/Generate detailing/i);
    await button.click();
    await expect.poll(async () => (await assemblies(page)).length).toBeGreaterThan(0);
    await expect(button).toHaveText(/Regenerate detailing/i);
  });

  test('D2c — regenerating increments the revision rather than resetting it', async ({ pro: page }) => {
    await generateDetailing(page);
    const before = Math.max(...(await assemblies(page))
      .map((a) => Number(a.detailingRevision)));
    await page.getByTestId('cmd-generate-detailing').click();
    await expect.poll(async () => Math.max(...(await assemblies(page))
      .map((a) => Number(a.detailingRevision)))).toBeGreaterThan(before);
  });

  test('D2d — detailing runs automatically after a design unless opted out', async ({ pro: page }) => {
    await loadModel(page, 'rc-design-qa-8');
    await openPanel(page);
    await expect(page.getByTestId('detailing-auto')).toBeChecked();
    await designAll(page);
    // No Generate click: the design run itself produced them.
    await expect.poll(async () => (await assemblies(page)).length, { timeout: 30_000 })
      .toBeGreaterThan(0);
  });

  test('D2e — the opt-out is honoured and the explicit command still works', async ({ pro: page }) => {
    await loadModel(page, 'rc-design-qa-8');
    await openPanel(page);
    await page.getByTestId('detailing-auto').uncheck();
    await designAll(page);
    expect(await assemblies(page)).toHaveLength(0);
    // Opting out of the automatic path must never remove the manual one.
    await page.getByTestId('cmd-generate-detailing').click();
    await expect.poll(async () => (await assemblies(page)).length).toBeGreaterThan(0);
  });
});

// ─── Inspection ──────────────────────────────────────────────────

test.describe('@smoke inspecting generated reinforcement', () => {
  test('D3 — the sheet preview renders geometry from the generated bars', async ({ pro: page }) => {
    await generateDetailing(page);
    await firstAssembly(page).click();
    const sheet = page.getByTestId('sheet-preview');
    await expect(sheet).toBeVisible();
    // A real drawing, not an empty frame: it contains drawn bar geometry.
    const svg = await sheet.innerHTML();
    expect(svg).toMatch(/<(path|line|polyline)/);
  });

  test('D4 — switching to the section view redraws', async ({ pro: page }) => {
    await generateDetailing(page);
    await firstAssembly(page).click();
    const before = await page.getByTestId('sheet-preview').innerHTML();
    await page.getByTestId('sheet-kind-section').click();
    await expect
      .poll(async () => await page.getByTestId('sheet-preview').innerHTML() !== before)
      .toBe(true);
  });

  test('D5 — the schedule totals the masses of the generated bars', async ({ pro: page }) => {
    await generateDetailing(page);
    await firstAssembly(page).click();
    const schedule = page.getByTestId('schedule');
    await expect(schedule).toBeVisible();
    const rows = schedule.locator('tbody tr');
    expect(await rows.count()).toBeGreaterThan(0);
    // The total must be positive and consistent with a real bar set.
    await expect(page.getByTestId('schedule-mass')).not.toHaveText(/^0([.,]0+)?\s*kg$/);
  });

  test('D6 — the panel is keyboard reachable and labelled', async ({ pro: page }) => {
    await generateDetailing(page);
    const list = page.getByRole('listbox').first();
    await expect(list).toHaveAttribute('aria-label', /.+/);
    const option = list.getByRole('option').first();
    await option.focus();
    await expect(option).toBeFocused();
  });

  test('D22 — selecting between assemblies switches the sheet', async ({ pro: page }) => {
    const n = await generateDetailing(page);
    test.skip(n < 2, 'needs at least two assemblies');
    const items = page.locator('[data-testid^="assembly-"]');
    await items.nth(0).click();
    const first = await page.getByTestId('sheet-preview').innerHTML();
    await items.nth(1).click();
    await expect
      .poll(async () => await page.getByTestId('sheet-preview').innerHTML() !== first)
      .toBe(true);
  });
});

// ─── The review gate ─────────────────────────────────────────────

test.describe('@smoke the review gate on generated work', () => {
  test('D7 — a review needs a named engineer', async ({ pro: page }) => {
    await generateDetailing(page);
    await firstAssembly(page).click();
    await openDocuments(page);
    await page.getByTestId('review-submit').click();
    await expect(page.getByTestId('review-error')).toBeVisible();
  });

  test('D9 — the review gate refuses while the assembly is below CONSTRUCTIBLE, and says why',
    async ({ pro: page }) => {
      await generateDetailing(page);
      await firstAssembly(page).click();

      // Real generated work does not arrive constructible: it carries whatever the
      // pipeline could not resolve. The product's job is to say so, not to let a
      // signature through.
      const state = await page.getByTestId('assembly-state').innerText();
      test.skip(/CONSTRUCTIBLE|REVIEWED/i.test(state), 'this model coordinated cleanly');

      await expect(page.getByTestId('state-blockers'),
        'an assembly stuck below CONSTRUCTIBLE must say what is blocking it')
        .toBeVisible();
      const blockers = await page.getByTestId('state-blockers').innerText();
      expect(blockers.length).toBeGreaterThan(20);

      await openDocuments(page);
      await page.getByTestId('review-engineer').fill('Ing. Bauti');
      await acknowledgeAll(page);
      await page.getByTestId('review-submit').click();
      await expect(page.getByTestId('review-error')).toBeVisible();
      // And the state did NOT advance.
      await expect(page.getByTestId('assembly-state')).toHaveText(state);
    });

  test('D9b — a review IS recorded against the revision when nothing blocks it',
    async ({ pro: page }) => {
      await generateDetailing(page);
      const all = await assemblies(page);
      const idx = all.findIndex((a) => a.state === 'CONSTRUCTIBLE');
      test.skip(idx < 0, 'this model produced no constructible assembly');

      await page.locator('[data-testid^="assembly-"]').nth(idx).click();
      const revision = Number(all[idx].detailingRevision);
      await openDocuments(page);
      await page.getByTestId('review-engineer').fill('Ing. Bauti');
      await acknowledgeAll(page);
      await page.getByTestId('review-submit').click();

      await expect.poll(async () => {
        const a = (await assemblies(page))[idx];
        return (a.review as { revision?: number } | undefined)?.revision;
      }).toBe(revision);
    });

  test('D11 — the review record states that software approval is not sign-off',
    async ({ pro: page }) => {
      await generateDetailing(page);
      await firstAssembly(page).click();
      // The disclaimer belongs to the review surface and must be present before any
      // signature, not after it.
      await openDocuments(page);
      await expect(page.getByTestId('review-disclaimer'))
        .toContainText(/not.*signature|no constituye firma|not.*sign-off/i);
      await expect(page.getByTestId('review-engineer')).toBeVisible();
    });

  test('D13 — provisional work is listed for explicit acknowledgement',
    async ({ pro: page }) => {
      await generateDetailing(page);
      await firstAssembly(page).click();
      await openDocuments(page);
      const acks = page.getByTestId('provisional-ack');
      const n = await acks.count();
      test.skip(n === 0, 'this model produced no provisional items');
      // Each provisional item is its own checkbox: acknowledging "everything" in one
      // click is how provisional work gets waved through.
      expect(await page.locator('[data-testid^="ack-"]').count()).toBe(n);
    });

  test('D19 — regenerating clears a review that no longer describes the bars',
    async ({ pro: page }) => {
      await generateDetailing(page);
      const all = await assemblies(page);
      const idx = all.findIndex((a) => a.state === 'CONSTRUCTIBLE');
      test.skip(idx < 0, 'this model produced no constructible assembly');

      await page.locator('[data-testid^="assembly-"]').nth(idx).click();
      await openDocuments(page);
      await page.getByTestId('review-engineer').fill('Ing. Bauti');
      await acknowledgeAll(page);
      await page.getByTestId('review-submit').click();
      await expect(page.getByTestId('assembly-state')).toContainText(/REVIEWED/i);

      await page.getByTestId('cmd-generate-detailing').click();
      await expect(page.getByTestId('assembly-state')).not.toContainText(/^REVIEWED$/i);
    });
});

/** Tick every provisional acknowledgement the review dialog asks for. */
async function acknowledgeAll(page: Page) {
  await openDocuments(page);
  const boxes = page.locator('[data-testid^="ack-"]');
  const n = await boxes.count();
  for (let i = 0; i < n; i++) await boxes.nth(i).check();
}

// ─── Honesty about what the pipeline could not do ────────────────

test.describe('@smoke the panel is honest about generated results', () => {
  test('D12 — a provisional assembly is badged before anyone signs it', async ({ pro: page }) => {
    await generateDetailing(page);
    const all = await assemblies(page);
    const provisional = all.filter((a) => a.maturity !== 'VALIDATED');
    test.skip(provisional.length === 0, 'this model produced no provisional work');
    await expect(page.locator('.maturity, [data-testid^="assembly-maturity"]').first())
      .toBeVisible();
  });

  test('D17 — a clean assembly says so rather than showing an empty list', async ({ pro: page }) => {
    await generateDetailing(page);
    await firstAssembly(page).click();
    const conflicts = (await assemblies(page))[0].conflicts as unknown[];
    if (conflicts.length === 0) {
      await expect(page.getByTestId('no-conflicts')).toBeVisible();
    } else {
      await expect(page.getByTestId('conflict-nav')).toBeVisible();
    }
  });

  test('D16 — conflicts, when the pipeline finds them, are navigable one at a time',
    async ({ pro: page }) => {
      await generateDetailing(page);
      const withConflicts = (await assemblies(page))
        .findIndex((a) => (a.conflicts as unknown[]).length > 1);
      test.skip(withConflicts < 0, 'this model coordinated cleanly');
      await page.locator('[data-testid^="assembly-"]').nth(withConflicts).click();
      const label = page.getByTestId('conflict-counter');
      const before = await label.innerText();
      await page.getByTestId('conflict-next').click();
      await expect(label).not.toHaveText(before);
    });

  test('D18 — an unsupported condition is listed rather than hidden', async ({ pro: page }) => {
    await generateDetailing(page);
    const idx = (await assemblies(page))
      .findIndex((a) => (a.unsupported as unknown[]).length > 0);
    test.skip(idx < 0, 'this model hit no unsupported condition');
    await page.locator('[data-testid^="assembly-"]').nth(idx).click();
    await expect(page.getByTestId('unsupported-list')).toBeVisible();
  });
});

// ─── Persistence and locking ─────────────────────────────────────

test.describe('@smoke generated detailing persists and respects locks', () => {
  test('D20 — assemblies survive a model snapshot round-trip', async ({ pro: page }) => {
    await generateDetailing(page);
    const before = await assemblies(page);
    // Undo then redo exercises the same snapshot path as save/load and tab switching.
    await page.keyboard.press('Control+z');
    await page.keyboard.press('Control+Shift+z');
    await expect.poll(async () => (await assemblies(page)).length).toBe(before.length);
  });

  test('D21 — a locked bar survives regeneration untouched', async ({ pro: page }) => {
    await generateDetailing(page);
    await firstAssembly(page).click();
    await page.getByTestId('bar-list').locator('summary').click();
    const lock = page.getByTestId('bar-lock').first();
    test.skip(await lock.count() === 0, 'no lock control rendered for this assembly');
    await lock.click();

    const lockedIds = (await assemblies(page)).flatMap((a) =>
      (a.bars as Array<{ id: string; locked?: boolean }>)
        .filter((b) => b.locked).map((b) => b.id));
    expect(lockedIds.length).toBeGreaterThan(0);

    await page.getByTestId('cmd-generate-detailing').click();
    await expect.poll(async () => {
      const after = (await assemblies(page)).flatMap((a) =>
        (a.bars as Array<{ id: string }>).map((b) => b.id));
      return lockedIds.every((id) => after.includes(id));
    }).toBe(true);
  });
});
