/**
 * Verified moving-load data for the landing's truss illustration.
 *
 * WHAT THIS IS
 * A six-panel simply-supported Pratt deck truss, solved offline by the plane
 * -truss direct stiffness method. The numbers below are the solved response,
 * not artistic values: the illustration reads them, it does not invent them.
 *
 * MODEL
 *   Span      6 panels x 80 units, deck (bottom chord) at y = 130, top chord
 *             at y = 30. Inclined end posts, five verticals, four Pratt
 *             diagonals sloping down toward midspan.
 *   Statics   12 nodes, 21 members, 3 reactions -> 2n = m + r = 24, so the
 *             truss is statically determinate and stable.
 *   Supports  B0 pinned (ux = uy = 0), B6 roller (uy = 0). Both are deck nodes,
 *             and the drawn support symbols sit on those node coordinates.
 *   Sections  EA = 1 for every member (uniform, normalised).
 *   Load      A single downward unit load, P = 1, applied to the deck.
 *
 * SOLUTION
 * One load case per deck panel point B0..B6. Reactions come out at the exact
 * statics values (load at B1 -> 5/6 and 1/6, at B3 -> 1/2 and 1/2, and so on),
 * vertical equilibrium closes to 1.0 in every case, and load positions
 * mirrored about midspan produce exactly mirrored member forces.
 *
 * BETWEEN PANEL POINTS
 * The load is distributed linearly to the two adjacent deck nodes -- at 30 %
 * of a panel, 70 % goes to the near node and 30 % to the far one, so the total
 * applied load stays exactly 1. The structure is linear-elastic, so the
 * response for that split is the same linear blend of the two panel-point
 * solutions. The component therefore interpolates FORCES and DISPLACEMENTS
 * with the same weights, which is exact rather than an approximation.
 *
 * SIGN CONVENTION
 * Member force positive = tension, negative = compression. `FORCE_MAX` is the
 * largest magnitude over every case and is used as a single global colour
 * scale, so intensity is comparable between frames.
 *
 * DISPLACEMENTS
 * `DISPLACEMENTS[case]` is [ux, uy] per node in node order, computed with
 * EA = 1 and P = 1. They are not physical millimetres; `DISP_SCALE` maps the
 * largest deflection in the whole dataset (851.43 units) onto
 * 22 px of drawing, which is why the legend says normalised
 * rather than quoting an amplification factor that would only mean something
 * next to a real EA.
 *
 * Regenerated by hand only. See the tests in ./__tests__/truss-data.test.ts,
 * which re-derive the reactions and the symmetry from this table.
 */

export type TrussNode = { id: string; x: number; y: number };
export type TrussMember = { a: string; b: string; kind: 'bottom' | 'top' | 'post' | 'vertical' | 'diagonal' };

export const NODES: TrussNode[] = [
  { id: 'B0', x: 40, y: 130 },
  { id: 'B1', x: 120, y: 130 },
  { id: 'B2', x: 200, y: 130 },
  { id: 'B3', x: 280, y: 130 },
  { id: 'B4', x: 360, y: 130 },
  { id: 'B5', x: 440, y: 130 },
  { id: 'B6', x: 520, y: 130 },
  { id: 'T1', x: 120, y: 30 },
  { id: 'T2', x: 200, y: 30 },
  { id: 'T3', x: 280, y: 30 },
  { id: 'T4', x: 360, y: 30 },
  { id: 'T5', x: 440, y: 30 },
];

export const MEMBERS: TrussMember[] = [
  { a: 'B0', b: 'B1', kind: 'bottom' },
  { a: 'B1', b: 'B2', kind: 'bottom' },
  { a: 'B2', b: 'B3', kind: 'bottom' },
  { a: 'B3', b: 'B4', kind: 'bottom' },
  { a: 'B4', b: 'B5', kind: 'bottom' },
  { a: 'B5', b: 'B6', kind: 'bottom' },
  { a: 'T1', b: 'T2', kind: 'top' },
  { a: 'T2', b: 'T3', kind: 'top' },
  { a: 'T3', b: 'T4', kind: 'top' },
  { a: 'T4', b: 'T5', kind: 'top' },
  { a: 'B0', b: 'T1', kind: 'post' },
  { a: 'B6', b: 'T5', kind: 'post' },
  { a: 'T1', b: 'B1', kind: 'vertical' },
  { a: 'T2', b: 'B2', kind: 'vertical' },
  { a: 'T3', b: 'B3', kind: 'vertical' },
  { a: 'T4', b: 'B4', kind: 'vertical' },
  { a: 'T5', b: 'B5', kind: 'vertical' },
  { a: 'T1', b: 'B2', kind: 'diagonal' },
  { a: 'T2', b: 'B3', kind: 'diagonal' },
  { a: 'T5', b: 'B4', kind: 'diagonal' },
  { a: 'T4', b: 'B3', kind: 'diagonal' },
];

/** Deck nodes, left to right: the load path and the panel points. */
export const DECK: string[] = NODES.filter((n) => n.id.startsWith('B')).map((n) => n.id);

export const SUPPORTS = [
  { node: 'B0', kind: 'pinned' as const },
  { node: 'B6', kind: 'roller' as const },
];

/** Axial force per member, one row per unit load at DECK[i]. + tension. */
export const FORCES: number[][] = [
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0.6667, 0.6667, 0.5333, 0.2667, 0.1333, 0.1333, -0.5333, -0.4, -0.4, -0.2667, -1.0672, -0.2134, 1, 0.1667, 0, -0.1667, 0, -0.2134, -0.2134, 0.2134, 0.2134],
    [0.5333, 0.5333, 1.0667, 0.5333, 0.2667, 0.2667, -1.0667, -0.8, -0.8, -0.5333, -0.8537, -0.4269, 0, 0.3333, 0, -0.3333, 0, 0.8537, -0.4269, 0.4269, 0.4269],
    [0.4, 0.4, 0.8, 0.8, 0.4, 0.4, -0.8, -1.2, -1.2, -0.8, -0.6403, -0.6403, 0, -0.5, 0, -0.5, 0, 0.6403, 0.6403, 0.6403, 0.6403],
    [0.2667, 0.2667, 0.5333, 1.0667, 0.5333, 0.5333, -0.5333, -0.8, -0.8, -1.0667, -0.4269, -0.8537, 0, -0.3333, 0, 0.3333, 0, 0.4269, 0.4269, 0.8537, -0.4269],
    [0.1333, 0.1333, 0.2667, 0.5333, 0.6667, 0.6667, -0.2667, -0.4, -0.4, -0.5333, -0.2134, -1.0672, 0, -0.1667, 0, 0.1667, 1, 0.2134, 0.2134, -0.2134, -0.2134],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
];

/** [ux, uy] per node, flattened, one row per unit load at DECK[i]. EA = 1. */
export const DISPLACEMENTS: number[][] = [
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 53.33, 437.02, 106.67, 378.68, 149.33, 335.41, 170.67, 240.94, 181.33, 129, 192, 0, 202.5, 337.02, 159.83, 362.01, 127.83, 335.41, 95.83, 257.61, 74.5, 129],
    [0, 0, 42.67, 378.68, 85.33, 689.1, 170.67, 619.62, 213.33, 447.75, 234.67, 240.94, 256, 0, 298.33, 378.68, 213, 655.76, 149, 619.62, 85, 481.08, 42.33, 240.94],
    [0, 0, 32, 335.41, 64, 619.62, 128, 851.43, 192, 619.62, 224, 335.41, 256, 0, 288, 335.41, 224, 669.62, 128, 851.43, 32, 669.62, -32, 335.41],
    [0, 0, 21.33, 240.94, 42.67, 447.75, 85.33, 619.62, 170.67, 689.1, 213.33, 378.68, 256, 0, 213.67, 240.94, 171, 481.08, 107, 619.62, 43, 655.76, -42.33, 378.68],
    [0, 0, 10.67, 129, 21.33, 240.94, 42.67, 335.41, 85.33, 378.68, 138.67, 437.02, 192, 0, 117.5, 129, 96.17, 257.61, 64.17, 335.41, 32.17, 362.01, -10.5, 337.02],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
];

/** Largest |axial force| anywhere in the dataset — the global colour scale. */
export const FORCE_MAX = 1.2;

/** Below this the member is drawn as near-zero (neutral grey). */
export const FORCE_EPS = 0.02;

/** Multiplier from computed displacement to drawn pixels. */
export const DISP_SCALE = 0.025839;

/** Members that genuinely reverse sign as the load crosses the span. */
export const REVERSING_MEMBERS = ['T2-B2', 'T4-B4', 'T1-B2', 'T2-B3', 'T4-B3', 'T5-B4'];

/**
 * Blend the two bracketing panel-point solutions for a load at `s` in [0, 1]
 * along the deck. Returns forces, nodal displacements and the applied nodal
 * load vector, whose entries always sum to exactly 1.
 */
export function stateAt(s: number) {
  const t = Math.min(1, Math.max(0, s)) * (DECK.length - 1);
  const i = Math.min(DECK.length - 2, Math.floor(t));
  const w = t - i;
  const mix = (rows: number[][]) => rows[i].map((v, k) => v * (1 - w) + rows[i + 1][k] * w);
  const load = DECK.map((_, k) => (k === i ? 1 - w : k === i + 1 ? w : 0));
  return { forces: mix(FORCES), displacements: mix(DISPLACEMENTS), load, panel: i, fraction: w };
}
