/**
 * What CIRSOC 201 support actually means, per edition, per facet.
 *
 * This file is the honest answer to "what can the app do?". Every declaration below was
 * written by checking what the code in this branch actually executes — not what it
 * aspires to. Where a facet is false, `limitation` says why in words the user sees.
 *
 * Reading guide for the five facets (see ../../../codes/capability.ts):
 *   verify      given a design, decide pass/fail against the code
 *   generate    produce a compliant design, not merely rate one
 *   coordinate  make it consistent across adjacent members
 *   document    draw and schedule it well enough for an engineer to review
 *   gate        an unsupported verify blocks the model reaching a complete state
 *
 * The gate facet is set on everything whose absence would otherwise let a floor be
 * reported as complete while a required check was never performed.
 */

import { clause } from '../../../codes/regulation';
import type { RegulationEdition } from '../../../codes/regulation';
import { transverseSpacingSupportedForEdition } from '../../../codes/cirsoc201/transverse-spacing';
import {
  emptyMatrix, facets, type CapabilityMatrix,
} from '../../../codes/capability';

const C25 = (c: string, label?: string) => clause('cirsoc-201', '2025', c, label);
const C05 = (c: string, label?: string) => clause('cirsoc-201', '2005', c, label);

/** Clause lists surfaced in certificates, per edition. Never mixed. */
export const CIRSOC201_CLAUSES: Record<RegulationEdition, string[]> = {
  // Chapters 9 (vigas), 10 (columnas), 21 (factores φ), 22 (resistencia de secciones),
  // 25 (detalles de armado) of the 2025 edition.
  '2025': ['§9.5', '§9.6', '§9.7', '§10.5', '§10.6', '§10.7', '§21.2', '§22.2', '§22.5', '§25.2', '§25.4'],
  // The 2005 edition numbers the same subject matter entirely differently.
  '2005': ['§10.2', '§10.3', '§10.5', '§10.9.1', '§11.2', '§11.5', '§7.6.1', '§7.10.5', '§12.2'],
  '2018': [],
  '2024': [],
};

function buildMatrix(edition: RegulationEdition): CapabilityMatrix {
  const c = edition === '2025' ? C25 : C05;
  const m = emptyMatrix();

  const flexureRefs = edition === '2025'
    ? [c('9.5', 'resistencia de cálculo a flexión'), c('22.2', 'resistencia a flexión'), c('21.2', 'factores φ')]
    : [c('10.2'), c('10.3'), c('9.3')];
  const shearRefs = edition === '2025'
    ? [c('9.5.3', 'corte'), c('22.5', 'resistencia al corte de una sección')]
    : [c('11.2'), c('11.5')];

  // ── Beams and columns: verified, and generated by the bounded candidate search ──
  //
  // EXCEPT under 2005. The transverse-spacing rule (Table 9.7.6.2.2) is implemented for the
  // 2025 edition only: the 2005 text is not supplied with this repository, so its §11.5.5
  // rule cannot be applied, and the 2025 table is deliberately NOT substituted for it. A
  // certificate stamped "CIRSOC 201-2005" whose governing stirrup spacing came from the 2025
  // table would cite a rule it never applied — conservative, but misattributed.
  //
  // Shear and ties therefore lose `verify` and `generate` under 2005 while KEEPING `gate`,
  // which is the honest combination: the app cannot decide the check, and a member it cannot
  // decide may not be counted complete.
  const transverseImplemented = transverseSpacingSupportedForEdition(edition);
  const shearFacets = transverseImplemented
    ? facets({ verify: true, generate: true, gate: true })
    : facets({ gate: true });
  const transverseLimitation = transverseImplemented ? undefined
    : 'La separación de la armadura transversal sólo está implementada para la edición ' +
      '2025 (Tabla 9.7.6.2.2). El texto 2005 no se distribuye con la aplicación y su regla ' +
      'no puede aplicarse; la tabla 2025 no se sustituye porque el resultado citaría una ' +
      'regla que nunca se aplicó. Diseñe con la edición 2025.';

  m.beamFlexure = { facets: facets({ verify: true, generate: true, gate: true }), refs: flexureRefs };
  m.beamShear = { facets: shearFacets, refs: shearRefs, limitation: transverseLimitation };
  m.columnAxialFlexure = {
    facets: facets({ verify: true, generate: true, gate: true }),
    refs: edition === '2025'
      ? [c('10.5.2', 'fuerza axial y momento'), c('22.4', 'resistencia axial')]
      : [c('10.3'), c('10.9')],
  };
  m.columnBiaxial = {
    facets: facets({ verify: true, generate: true, gate: true }),
    refs: edition === '2025' ? [c('22.4.2')] : [c('10.3.6')],
  };
  m.columnSlenderness = {
    facets: facets({ verify: true, gate: true }),
    refs: edition === '2025' ? [c('6.6.4', 'método del momento magnificado')] : [c('10.12')],
    limitation:
      'El magnificador de esbeltez se verifica con el valor suministrado; el app no ' +
      'genera una sección alternativa por esbeltez.',
  };
  m.ties = {
    facets: shearFacets,
    refs: edition === '2025' ? [c('10.7.6', 'armadura transversal'), c('25.7.2', 'estribos')] : [c('7.10.5')],
    limitation: transverseLimitation,
  };
  m.beamRegions = {
    facets: facets({ verify: true, generate: true }),
    refs: edition === '2025' ? [c('9.7.3', 'desarrollo de la armadura de flexión')] : [c('12.10')],
  };
  m.anchorage = {
    facets: facets({ verify: true }),
    refs: edition === '2025' ? [c('25.4', 'longitudes de anclaje')] : [c('12.2')],
    limitation:
      'Se verifica la longitud disponible contra la requerida. El app no genera ganchos, ' +
      'barras de anclaje ni prolongaciones para resolver un anclaje insuficiente.',
  };

  // ── The corrected over-claim ──
  m.curtailment = {
    facets: facets({ verify: true }),
    refs: edition === '2025' ? [c('9.7.3.2'), c('9.7.3.3'), c('9.7.3.5')] : [c('12.10'), c('12.11')],
    limitation:
      'El app verifica una interrupción de barras suministrada por el usuario, pero no la ' +
      'genera. Generar puntos de corte coordinados a lo largo de una línea de vigas es ' +
      'trabajo de la rama de detallado coordinado.',
  };

  m.beamTorsion = {
    facets: facets({ gate: true }),
    refs: edition === '2025' ? [c('9.5.4', 'torsión'), c('22.7')] : [c('11.6')],
    limitation:
      'No se verifica torsión. Un elemento con torsión significativa no puede declararse ' +
      'verificado; el resultado se marca como no soportado.',
  };
  m.nonRectangularSections = {
    facets: facets({ gate: true }),
    refs: edition === '2025' ? [c('22.2')] : [c('10.2')],
    limitation: 'Sólo se soportan secciones rectangulares. Secciones T, L y circulares no se verifican.',
  };
  m.lapsSplices = {
    facets: facets({ verify: true }),
    refs: edition === '2025' ? [c('25.5', 'empalmes')] : [c('12.15')],
    limitation: 'Se calcula la longitud de empalme requerida; no se generan ni se escalonan empalmes.',
  };
  m.bentBars = {
    facets: facets({}),
    refs: edition === '2025' ? [c('9.7.3.7', 'barras dobladas'), c('25.3', 'diámetros de doblado')] : [c('12.12')],
    limitation: 'Las barras dobladas o levantadas no se generan ni se dibujan.',
  };
  m.joints = {
    facets: facets({ gate: true }),
    refs: edition === '2025' ? [c('15.2', 'nudos viga-columna')] : [c('11.10')],
    limitation: 'Los nudos viga-columna no se modelan geométricamente.',
  };
  m.jointShear = {
    facets: facets({ gate: true }),
    refs: edition === '2025' ? [c('15.4', 'resistencia al corte del nudo')] : [c('11.10')],
    limitation:
      'No se verifica el corte en el nudo. Requiere un cuerpo libre por combinación cuya ' +
      'validación aún no está satisfecha.',
  };

  // ── Element families this branch does not touch ──
  const family = (refs2025: string[], refs2005: string[], what: string) => ({
    facets: facets({ gate: true }),
    refs: (edition === '2025' ? refs2025 : refs2005).map((x) => c(x)),
    limitation: `${what} no se diseñan ni se verifican en esta versión.`,
  });
  m.slabsOneWay = family(['7.1'], ['13.1'], 'Las losas en una dirección');
  m.slabsTwoWay = family(['8.1'], ['13.5'], 'Las losas en dos direcciones');
  m.walls = family(['11.1'], ['14.1'], 'Los tabiques');
  m.foundations = family(['13.1'], ['15.1'], 'Las fundaciones');
  m.diaphragms = family(['12.1'], ['21.9'], 'Los diafragmas');

  // ── Seismic: governed by INPRES-CIRSOC 103, not by CIRSOC 201 ──
  m.seismicAnalysis = {
    facets: facets({ gate: true }),
    refs: [clause('inpres-cirsoc-103-i', '2018', '6.1', 'método estático')],
    limitation:
      'El análisis sísmico según INPRES-CIRSOC 103 no está productizado. El solver ' +
      'dispone de análisis modal y espectral, pero el app no define una fuente de masa ' +
      'real ni genera la acción sísmica reglamentaria.',
  };
  m.seismicDetailing = {
    facets: facets({ gate: true }),
    refs: [clause('inpres-cirsoc-103-ii', '2005', '2.1', 'pórticos sismorresistentes')],
    limitation:
      'El detallado sismorresistente de INPRES-CIRSOC 103 Parte II no está implementado. ' +
      'Mientras tanto, los elementos de un proyecto sísmico no pueden declararse ' +
      'completamente detallados.',
  };

  // ── Output ──
  m.barSchedules = {
    facets: facets({ document: true }),
    refs: edition === '2025' ? [c('26.4', 'documentos de construcción')] : [],
    limitation:
      'Se emite una planilla aproximada de barras. Las longitudes de corte todavía no ' +
      'provienen de una geometría física de barras con doblados reales.',
  };
  m.floorPlans = {
    facets: facets({}),
    refs: edition === '2025' ? [c('26.4')] : [],
    limitation: 'No se generan planos de replanteo ni de armado de plantas completas.',
  };

  return Object.freeze(m) as CapabilityMatrix;
}

export const CIRSOC201_CAPABILITIES_2025: CapabilityMatrix = buildMatrix('2025');
export const CIRSOC201_CAPABILITIES_2005: CapabilityMatrix = buildMatrix('2005');
